export const CLIENT_STYLE = {
  DIALOG_TITLE: { background: "#2057be", p: 1.5 },
  DIALOG_TASK_TITLE: { background: "#03ca8e", p: 1.3, color: "#000000" },
  DIALOG_ACTIONS_STYLE: {
    gap: 1.2,
    mb: 1,
    px: 3,
    pb: 2,

    "& .MuiButton-root": {
      fontSize: ".90rem",
      fontWeight: 600,
      textTransform: "none",
      px: 3,
      py: 1,
      borderRadius: 2,
    },
  },
  DIALOG_ACTION_BUTTON_CANCEL: {
    backgroundColor: "#dc2626",
    color: "#fff",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#921717",
    },
  },
  DIALOG_ACTION_BUTTON_SAVE: {
    backgroundColor: "#1c974e",
    color: "#fff",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#0e6631",
    },
  },
  FIELD_ACTION_BUTTON_ACTIVATE_SITE: {
    backgroundColor: "#fd4e4e",
    color: "#000000",
    width: 100,
    minWidth: 120,
    pb: 0.9,
    pt: 0.9,
    fontSize: "1.8ex",
    fontWeight: 600,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#941818",
      color: "#eee7e7",
    },
  },
  FIELD_ACTION_BUTTON_SITE_ACTIVE: {
    backgroundColor: "#86e935",
    width: 100,
    minWidth: 120,
    pb: 0.9,
    pt: 0.9,
    fontWeight: 600,
    fontSize: "1.8ex",
    color: "#000000",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#487c1d",
      color: "#ffffff",
    },
  },
  SITE_FIELD: {
    background: "#2057be",
    width: 300,
    minWidth: 120,
    cursor: "pointer",
    color: "#fff",
    display: "-webkit-box",
    textAlign: "center",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
    overflow: "hidden",
    fontWeight: 600,
    borderRadius: 2,
    pb: 0.9,
    pt: 0.9,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#13336d",
      color: "#fff",
    },
  },
  SITE_FIELD_EMPTY: {
    background: "#13336d",
    width: 300,
    minWidth: 120,
    cursor: "pointer",
    color: "#fff",
    display: "-webkit-box",
    textAlign: "center",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
    overflow: "hidden",
    fontWeight: 600,
    borderRadius: 2,
    pb: 0.9,
    pt: 0.9,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#2057be",
      color: "#fff",
    },
  },
  SELECT_PAYMENT: {
    widith: 300,
    minWidth: 120,
    fontSize: "0.9rem",
    background: "#a3a3a3",
    color: "#000000",
    borderRadius: 2,
    fontWeight: 600,
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    BorderAllOutlined: "none",
    transition: "all 0.15s ease-in-out",
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&:hover": {
      backgroundColor: "#919191",
      color: "#fff",
    },
  },
  NO_PAYMENT: {
    widith: 300,
    minWidth: 120,
    fontSize: "0.9rem",
    background: "#464646",
    borderRadius: 2,
    fontWeight: 600,
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    transition: "all 0.15s ease-in-out",
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "&:hover": {
      backgroundColor: "#646464",
    },
  },
  TASK_FIELD: {
    background: "#04df9d",
    width: 200,
    minWidth: 120,
    cursor: "pointer",
    color: "#000000",
    display: "-webkit-box",
    textAlign: "center",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
    overflow: "hidden",
    fontWeight: 600,
    borderRadius: 2,
    pb: 0.9,
    pt: 0.9,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#04a374",
      color: "#fff",
    },
  },
  TASK_EMPTY: {
    background: "#464646",
    color: "#ffffff",
    width: 200,
    minWidth: 120,
    cursor: "pointer",
    display: "-webkit-box",
    textAlign: "center",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
    overflow: "hidden",
    fontWeight: 600,
    borderRadius: 2,
    pb: 0.9,
    pt: 0.9,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#363636",
    },
  },
};
