export const LEAD_STYLE = {
  DIALOG_TITLE: { background: "#ac6727ff", p:1.5 },
  DIALOG_ACTIONS_STYLE: {
    gap: 1.2,
    mb: 1,
    px: 3,
    pb: 2,

    "& .MuiButton-root": {
      fontSize: ".90rem",
      fontWeight: 600,
      textTransform: "none",
      px: 3,
      py: 1,
      borderRadius: 2,
    },
  },
  DIALOG_ACTION_BUTTON_CANCEL: {
    backgroundColor: "#dc2626",
    color: "#fff",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#921717",
    },
  },
  DIALOG_ACTION_BUTTON_SAVE: {
    backgroundColor: "#1c974e",
    color: "#fff",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#0e6631",
    },
  },
  DIALOG_ACTION_BUTTON_ACTIVATE_CLIENT: {
    backgroundColor: "#e78b44",
    color: "#2e2d2d",
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#c46a22",
    },
  },
  DIALOG_ACTION_BUTTON_CLIENT_ACTIVE: {
    backgroundColor: "#2e4570",
    color: "#ffffff",
  },
  FIELD_ACTION_BUTTON_ACTIVATE_CLIENT: {
    backgroundColor: "#57ebff",
    color: "#1a1919",
    width: 200,
    minWidth: 120,
    pb: 0.9,
    pt: 0.9,
    fontSize: "1.8ex",
    fontWeight: 600,
    transition: "all 0.15s ease-in-out",
    "&:hover": {
      backgroundColor: "#4590b3",
      color: "#eee7e7",
    },
  },
  FIELD_ACTION_BUTTON_CLIENT_ACTIVE: {
    backgroundColor: "#0e4e5e",
    width: 200,
    minWidth: 120,
    pb: 0.9,
    pt: 0.9,
    fontWeight: 600,
    fontSize: "1.8ex",
    color: "#ffffff",
  },
  DATAGRID_STYLE: {
    backgroundColor: "#111827",
    borderRadius: 2,
    "& .RaDatagrid-headerCell": {
      backgroundColor: "#0a7995",
      color: "#f0f2f7ff",
      fontWeight: 800,
      fontSize: "1.10rem",
      transition: "all 0.15s ease-in-out",
    },
    // "& .RaDatagrid-row:hover": {
    //   backgroundColor: "#000000",
    // },
    EMAIL_FIELD: { color: "#fff", textDecoration: "underline" },
    COMMENT_FIELD: {
      background: "#ac6727ff",
      width: 400,
      minWidth: 120,
      cursor: "pointer",
      color: "#fff",
      display: "-webkit-box",
      textAlign: "center",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 1,
      overflow: "hidden",
      fontWeight: 600,
      borderRadius: 2,
      pb: 0.6,
      pt: 0.6,
      transition: "all 0.15s ease-in-out",
      "&:hover": {
        backgroundColor: "#814e1eff",
        color: "#fff",
      },
    },
    COMMENT_FIELD_EMPTY: {
      background: "#613a15ff",
      width: 400,
      minWidth: 120,
      cursor: "pointer",
      color: "#fff",
      display: "-webkit-box",
      textAlign: "center",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 1,
      overflow: "hidden",
      fontWeight: 600,
      borderRadius: 2,
      pb: 0.6,
      pt: 0.6,
      transition: "all 0.15s ease-in-out",
      "&:hover": {
        backgroundColor: "#ac6727ff",
        color: "#fff",
      },
    },
    SELECT: {
      widith: 300,
      minWidth: 120,
      fontSize: "0.9rem",
      background: "#119346",
      color: "#fff",
      borderRadius: 2,
      fontWeight: 600,
      display: "flex",
      justifyContent: "center",
      textAlign: "center",
      BorderAllOutlined: "none",
      transition: "all 0.15s ease-in-out",
      "& .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&:hover .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&:hover": {
        backgroundColor: "#0c6931ff",
      },
    },
    SELECT_NOPACKAGE: {
      widith: 300,
      minWidth: 120,
      fontSize: "0.9rem",
      background: "#013d19ff",
      borderRadius: 2,
      fontWeight: 600,
      display: "flex",
      justifyContent: "center",
      textAlign: "center",
      transition: "all 0.15s ease-in-out",
      "& .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&:hover .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
      "&:hover": {
        backgroundColor: "#286440ff",
      },
    },
  },
};
